language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer global require "fxp/composer-asset-plugin:~1.3"
  - composer install --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - phpunit --verbose